Stop forcing building with fake .git

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3661,14 +3661,16 @@ fi
 # -----------------------------------------------------------------------------
 
 # symlink includes
-if [ -z "$PERL" ]; then
-    echo
-    echo "You need perl in your PATH to make a build from GIT."
-    echo "Cannot proceed."
-    exit 1
-fi
+if [ -e "$relpath/.git" ]; then
+    if [ -z "$PERL" ]; then
+        echo
+        echo "You need perl in your PATH to make a build from GIT."
+        echo "Cannot proceed."
+        exit 1
+    fi
 
-"$relpath/bin/syncqt.pl" -minimal -module QtCore "$relpath" || exit 1
+    "$relpath/bin/syncqt.pl" -minimal -module QtCore "$relpath" || exit 1
+fi
 
 # $1: input variable name (awk regexp)
 # $2: optional output variable name
@@ -3798,11 +3800,11 @@ if true; then ###[ '!' -f "$outpath/bin/qmake" ];
 
         echo "BUILD_PATH = $adjoutpath" >> "$mkfile"
         echo "SOURCE_PATH = $adjrelpath" >> "$mkfile"
-        #if [ -e "$relpath/.git" ]; then
-        #    echo 'INC_PATH = $(BUILD_PATH)/include' >> "$mkfile"
-        #else
+        if [ -e "$relpath/.git" ]; then
+            echo 'INC_PATH = $(BUILD_PATH)/include' >> "$mkfile"
+        else
             echo 'INC_PATH = $(SOURCE_PATH)/include' >> "$mkfile"
-        #fi
+        fi
         echo "QMAKESPEC = $adjqmakespec" >> "$mkfile"
         echo "QT_VERSION = $QT_VERSION" >> "$mkfile"
         echo "EXTRA_CFLAGS = $EXTRA_CFLAGS" >> "$mkfile"
